// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5aZ1O4aappDWoSoL3NSEOJ45CfX2bQBc',
    appId: '1:323788035771:web:ca9e0b7318798b41bb7b9e',
    messagingSenderId: '323788035771',
    projectId: 'calender-app-f2d8a',
    authDomain: 'calender-app-f2d8a.firebaseapp.com',
    storageBucket: 'calender-app-f2d8a.appspot.com',
    measurementId: 'G-YNC5Z3SXSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwkyNmqYKkXvcfzIaoXQheFBZIzoLya6Q',
    appId: '1:323788035771:android:226c73f31a8a2bd1bb7b9e',
    messagingSenderId: '323788035771',
    projectId: 'calender-app-f2d8a',
    storageBucket: 'calender-app-f2d8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgmOGwnt_bAv87jnHNPm83i8zqjAGw_Lk',
    appId: '1:323788035771:ios:ddfacaca87de798bbb7b9e',
    messagingSenderId: '323788035771',
    projectId: 'calender-app-f2d8a',
    storageBucket: 'calender-app-f2d8a.appspot.com',
    iosBundleId: 'com.example.calenderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgmOGwnt_bAv87jnHNPm83i8zqjAGw_Lk',
    appId: '1:323788035771:ios:ddfacaca87de798bbb7b9e',
    messagingSenderId: '323788035771',
    projectId: 'calender-app-f2d8a',
    storageBucket: 'calender-app-f2d8a.appspot.com',
    iosBundleId: 'com.example.calenderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5aZ1O4aappDWoSoL3NSEOJ45CfX2bQBc',
    appId: '1:323788035771:web:69a5bcd4e6c67e61bb7b9e',
    messagingSenderId: '323788035771',
    projectId: 'calender-app-f2d8a',
    authDomain: 'calender-app-f2d8a.firebaseapp.com',
    storageBucket: 'calender-app-f2d8a.appspot.com',
    measurementId: 'G-WJ2F38F1KN',
  );
}
